# Generated by Django 5.2.7 on 2025-10-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('certificate_hash', models.CharField(max_length=256)),
                ('previous_hash', models.CharField(max_length=256)),
                ('nonce', models.IntegerField()),
                ('issuer', models.CharField(max_length=255)),
            ],
        ),
    ]
