# Generated by Django 5.2.7 on 2025-10-16 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('certificate_id', models.CharField(max_length=100, unique=True)),
                ('blockchain_hash', models.CharField(max_length=256)),
                ('status', models.CharField(default='Valid', max_length=50)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.institution')),
            ],
        ),
    ]
